Cutadapt
EBI-Metagenomics/nf-modules pull request #31
Opened 2024-01-16 15:23 UTC by chrisAta

There already exists a cutadapt nf-core module (https://github.com/nf-core/modules/blob/master/modules/nf-core/cutadapt/main.nf), but for the amplicon pipeline we need it to dynamically be able to change not just single/paired mode, but also which strands should get trimmed of primers (either both, just forward, or just reverse), so I copied the base of the module but also made a couple changes that will implement this behaviour

2024-01-16 16:08 UTC, vagkaratzas commented on modules/ebi-metagenomics/cutadapt/meta.yml
> +      pattern: "*.{fasta}"
if it's only one option, you can remove the brackets:
pattern: "*.fasta"

2024-01-16 16:17 UTC, vagkaratzas approved these changes
Very clever way to add the primer files. I am not very certain about the various conditions for rev_primer, but I think you would capture anything wrong with the tests.

2024-01-16 16:18 UTC, mberacochea requested changes
Good stuff.. I left one minor comment

2024-01-16 16:18 UTC, mberacochea commented on modules/ebi-metagenomics/cutadapt/main.nf
> +    def rev_primer = primers[1].size() > 0  && meta.single_end ? "-a file:${primers[1]}" : primers[1].size() > 0  && !meta.single_end ? "-G file:${primers[1]}" : ''
I would split this as conventional "if" statements.. it's a bit hard to read IMO

2024-01-16 16:19 UTC, vagkaratzas commented on modules/ebi-metagenomics/cutadapt/main.nf
> +    label 'process_single'
label 'process_medium'
in nf-core. Make sure you got the preferred one here.

2024-01-16 16:20 UTC, vagkaratzas commented on modules/ebi-metagenomics/cutadapt/main.nf
> +    conda "bioconda::cutadapt=4.6"
Also, in nf-core they've stopped writing this and instead do this:
conda "${moduleDir}/environment.yml"
And the resepctive file:
name: cutadapt
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::cutadapt=3.4

2024-01-16 16:33 UTC, KateSakharova approved these changes
Looks good to me, just resolve complains from nextflow-preacher :)

2024-01-17 16:14 UTC, chrisAta commented
Thanks everyone for the great feedback! I implemented all the changes now so I think it's ready 🚀

2024-01-17 16:18 UTC, mberacochea approved these changes
:shipit:

2024-01-17 16:21 UTC, merged