Module/seqfu/check
EBI-Metagenomics/nf-modules pull request #62
Opened 2024-09-10 11:10 UTC by chrisAta

2024-09-11 12:14 UTC, mberacochea commented on modules/ebi-metagenomics/seqfu/check/main.nf
> +        > ${prefix}_seqfu_out.tsv
I woulnd't use "_seqfu_out.tsv".. and just "${prefix}.tsv"

2024-09-11 12:21 UTC, mberacochea requested changes
Brilliant, SeqFu!

I've left you a few comments

2024-09-11 12:21 UTC, mberacochea commented on modules/ebi-metagenomics/seqfu/check/meta.yml
> +      tool_dev_url: "https://telatin.github.io/seqfu2/tools/derep.html"
```suggestion
      tool_dev_url: "https://telatin.github.io/seqfu2/tools/check.html"
```

2024-09-11 12:21 UTC, mberacochea commented on modules/ebi-metagenomics/seqfu/check/meta.yml
> +description: Perform sanity checking of FASTQ files
The description on the seqfu site is probably better?
"Evaluates the integrity of DNA FASTQ files."

2024-09-11 12:21 UTC, mberacochea commented on modules/ebi-metagenomics/seqfu/check/meta.yml
> +      pattern: "*.{fastq,fastq.gz}"
```suggestion
      pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
```

2024-09-11 12:21 UTC, mberacochea commented on modules/ebi-metagenomics/seqfu/check/tests/nextflow.config
> +        ext.args = '-s -d'
Maybe we should "hardcode" `-s`... just to avoid accidental issues if some forgets to load this file... happy to chat about this

2024-09-12 10:47 UTC, MGS-sails commented
Just left one comment. 
Otherwise seems fine to me.

2024-09-12 12:48 UTC, mberacochea approved these changes
:rocket:

2024-09-12 12:58 UTC, merged